# Generated by Django 5.2.6 on 2025-09-22 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='ticket',
        ),
    ]
