# Generated by Django 5.2.6 on 2025-09-22 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_attachment_ticket'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to='users.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to='users.user'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='remarks',
            field=models.TextField(blank=True, default='No remarks'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
