# Generated by Django 5.2.6 on 2025-09-25 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_tickethistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickethistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='tickethistory',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='tickethistory',
            name='note',
        ),
        migrations.RemoveField(
            model_name='tickethistory',
            name='old_status',
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(default='CREATED', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
