# Generated by Django 5.2.6 on 2025-09-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_tickethistory_changed_by_and_more'),
    ]

    operations = [
    ]
