# Generated by Django 5.2.6 on 2025-09-28 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_name'),
        ('tickets', '0009_ticket_email_ticket_file_ticket_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
    ]
