# Generated by Django 5.2.6 on 2025-09-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticket_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
