# Generated by Django 5.2.6 on 2025-09-29 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tickets', '0013_category_division_categories_alter_ticket_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
