# Generated by Django 5.2.6 on 2025-09-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ticket_category_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
