# Generated by Django 5.2.6 on 2025-10-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
