# Generated by Django 5.2.6 on 2025-10-09 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_ticket_due_date'),
    ]

    operations = [
    ]
