# Generated by Django 5.2.6 on 2025-11-20 04:15

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_ticket_completed_at_alter_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tickets.models.ticket_file_path),
        ),
    ]
