# Generated by Django 5.2.6 on 2025-09-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, help_text='Branch location for staff', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TECHNICIAN', 'Technician'), ('STAFF', 'Staff')], default='STAFF', help_text='Role of the user in the system', max_length=20),
        ),
    ]
